### ISSUE TITLE
Sender address is no longer the user who sent the email

### ISSUE THREAD

**Issue by upats** [lsuits/block_quickmail#230] opened 2017-09-05 19:46 UTC
When sending an email, the user who sent a message using Quickmail would have their email address in the "From" field. This way, when a receiver tried to reply to the email, it would go to the sender's inbox.

As of Quickmail 2017062200, emails appear to be sent from our site-wide noreply address. Obviously if someone attempts to reply to an email they received by Quickmail, they'll now get a "email address does not exist" response :(

Was this an intentional change at some point? I couldn't find a commit on 30-dev that explicitly removed this functionality and it looks like the function that actually sends the email wasn't changed.

**Comment by chadberg** [comment] 2017-09-07 13:53
Our semester also just started and this was reported to us by a faculty member. We'd like to revert to the previous behavior if possible.  Will filling in an 'alternate email' resolve this?

**Comment by chadmazilly** [comment] 2017-09-07 14:11
Hey guys, I'm going to take a look at this today and put up a patch. My guess is that it was a Moodle core change, but not really sure yet. Will keep you posted.

**Comment by chadmazilly** [comment] 2017-09-07 14:22
Ok just figured it out. This behavior is actually controlled by your individual User Profile settings. To control this, go to User Preferences > Edit Profile (yourmoodle.com/user/edit.php?id=[userid]) and take a look at your "Email Display" settings. Make sure this is not set to "Hide my email address from everyone". Let me know if that does the trick and I'll close this out.

**Comment by gedion** [comment] 2017-09-07 14:34
@chadmazilly. Just tried your suggestion and no luck.

**Comment by chadmazilly** [comment] 2017-09-07 14:38
@gedion What version of Moodle are you using?

**Comment by gedion** [comment] 2017-09-07 14:38
@chadmazilly. We're using 3.2

**Comment by chadmazilly** [comment] 2017-09-07 15:01
@gedion and what version of Quickmail are you using? are you installing through the moodle system or cloning from Github?

**Comment by gedion** [comment] 2017-09-07 15:08
@chadmazilly v1.7.1 (2017080300). I installed it through the Moodle system found in below url. 

https://moodle.org/plugins/pluginversions.php?plugin=block_quickmail

However the issue is also reported in v1.5.5 (2015122912) that we're currently running in our production system ( I have not tried your latest suggestion in this version)

**Comment by chadmazilly** [comment] 2017-09-07 15:18
@gedion One more thing to check, there is a Moodle config setting located at: (yourmoodle.com/admin/settings.php?section=messagesettingemail) that is called "Always send email from the no-reply address?" (emailonlyfromnoreplyaddress). I'd make sure that is unchecked.

**Comment by chadberg** [comment] 2017-09-07 15:38
I'm on 3.1, and this checkbox is not checked, but the issue persists.

**Comment by gedion** [comment] 2017-09-07 16:41
@chadmazilly. Such a setting does not exist in 3.2

**Comment by rrusso** [comment] 2017-09-07 16:43
https://moodle.org/mod/forum/discuss.php?d=341676

**Closed by rrusso** 2017-09-07 16:43 UTC

**Comment by rrusso** [comment] 2017-09-07 16:44
In Moodle 3.1 we are unable to replicate the issue. In Moodle 3.2 and above please see the above link.

**Comment by rrusso** [comment] 2017-09-07 16:45
https://tracker.moodle.org/browse/MDL-58038

**Comment by rrusso** [comment] 2017-09-07 16:46
https://tracker.moodle.org/browse/MDL-58517

**Comment by rrusso** [comment] 2017-09-07 16:46
https://tracker.moodle.org/browse/MDL-44467

**Comment by upats** [comment] 2017-09-07 17:41
Thanks Robert!

Adding our @up.edu domain to the "allowedemaildomains" is now allowing quickmail to send from individual users.

I figured it was a core moodle change since looking through your commits didn't reveal anything had changed.
